# Generated by Django 3.2.9 on 2021-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventUsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('weight_user', models.PositiveIntegerField(verbose_name='Масса')),
                ('age_user', models.PositiveIntegerField(verbose_name='Возраст')),
                ('text_a', models.CharField(max_length=55, verbose_name='Текст A')),
                ('text_b', models.CharField(max_length=55, verbose_name='Текст B')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Данные о пользователе мероприятия',
                'verbose_name_plural': 'Данные о пользователях мероприятия',
            },
        ),
    ]
